#pragma once

#include "Gameplay/ChangeDifficulty.hpp"
#include "Gameplay/ChangeSize.hpp"
#include "Gameplay/CreateSession.hpp"
#include "Gameplay/MovePlayer.hpp"
#include "Gameplay/Pause.hpp"
#include "Gameplay/RestartSession.hpp"
#include "Gameplay/ResumeGame.hpp"

#include "Menu/ScrollDown.hpp"
#include "Menu/ScrollUp.hpp"
#include "Menu/ScrollLeft.hpp"
#include "Menu/ScrollRight.hpp"
#include "Menu/Select.hpp"

#include "System/OpenGameOptions.hpp"
#include "System/OpenMainMenu.hpp"
#include "System/OpenPlayMenu.hpp"
#include "System/SwitchToLose.hpp"
#include "System/SwitchToWin.hpp"
#include "System/Terminate.hpp"
#include "System/SetupLoggerBoth.hpp"
#include "System/SetupLoggerConsole.hpp"
#include "System/SetupLoggerFile.hpp"
#include "System/SetupLoggerEmpty.hpp"
